// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// greedy_carving_cpp_raw
NumericVector greedy_carving_cpp_raw(NumericVector im, IntegerVector dim, int n_seams);
RcppExport SEXP _M2algorithmique_greedy_carving_cpp_raw(SEXP imSEXP, SEXP dimSEXP, SEXP n_seamsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type im(imSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< int >::type n_seams(n_seamsSEXP);
    rcpp_result_gen = Rcpp::wrap(greedy_carving_cpp_raw(im, dim, n_seams));
    return rcpp_result_gen;
END_RCPP
}
// greedy_carving_cpp
SEXP greedy_carving_cpp(SEXP im, int n_seams);
RcppExport SEXP _M2algorithmique_greedy_carving_cpp(SEXP imSEXP, SEXP n_seamsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type im(imSEXP);
    Rcpp::traits::input_parameter< int >::type n_seams(n_seamsSEXP);
    rcpp_result_gen = Rcpp::wrap(greedy_carving_cpp(im, n_seams));
    return rcpp_result_gen;
END_RCPP
}
// seam_carving_dp
SEXP seam_carving_dp(SEXP im, int n_seams);
RcppExport SEXP _M2algorithmique_seam_carving_dp(SEXP imSEXP, SEXP n_seamsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type im(imSEXP);
    Rcpp::traits::input_parameter< int >::type n_seams(n_seamsSEXP);
    rcpp_result_gen = Rcpp::wrap(seam_carving_dp(im, n_seams));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_M2algorithmique_greedy_carving_cpp_raw", (DL_FUNC) &_M2algorithmique_greedy_carving_cpp_raw, 3},
    {"_M2algorithmique_greedy_carving_cpp", (DL_FUNC) &_M2algorithmique_greedy_carving_cpp, 2},
    {"_M2algorithmique_seam_carving_dp", (DL_FUNC) &_M2algorithmique_seam_carving_dp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_M2algorithmique(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
