# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

greedy_carving_cpp_raw <- function(im, dim, n_seams) {
    .Call('_M2algorithmique_greedy_carving_cpp_raw', PACKAGE = 'M2algorithmique', im, dim, n_seams)
}

greedy_carving_cpp <- function(im, n_seams) {
    .Call('_M2algorithmique_greedy_carving_cpp', PACKAGE = 'M2algorithmique', im, n_seams)
}

seam_carving_dp <- function(im, n_seams) {
    .Call('_M2algorithmique_seam_carving_dp', PACKAGE = 'M2algorithmique', im, n_seams)
}

